"""Compatibility aliases for the diagnosis/reasoning call sites.

The Tier-1 reasoning code was written against singular class names; Phase 3's
`schema.py` (generated by sqlacodegen) uses pluralised names. This module simply
re-exports the canonical `schema.py` classes under the singular names -- it
defines no tables, so nothing is mapped twice. This extends the same pattern the
package already uses (`Founder = Founders`).
"""

from app.models.schema import (
    Answers as Answer,
    Founders as Founder,
    FounderStages as FounderStage,
    Questions as Question,
    Sessions as DiagnosisSession,
)

__all__ = ["Answer", "Founder", "FounderStage", "Question", "DiagnosisSession"]
