"""The invoice as a self-contained print document.

Self-contained is the requirement, not a preference: Gotenberg renders this in
a headless Chromium with no network of its own (see reports/gotenberg.py), so
an external stylesheet, webfont or logo URL would silently render as nothing.
The logo and the two type faces are base64-embedded by invoice_assets.py, and
everything else is inline.

The same HTML is also served to the browser, which is what keeps the on-screen
receipt and the downloaded PDF from drifting: there is one template, not a JSX
copy of one. That drift is the exact failure reports/print_html.py was written
to prevent, and there is no reason to relearn it here.

WHAT THE LAYOUT IS TRYING TO DO. A receipt is read by two people with opposite
needs. The founder wants one number -- what they were charged -- and wants to
believe the document is real. Their accountant wants the tax split, the
registration numbers and the references, and wants none of it to be pretty. So
the document leads with the amount and the paid stamp in a panel of their own,
then gives the accountant everything else in descending order of how often it
is looked at, and closes with the legal entity that issued it. Nothing here is
decoration for its own sake: the logo, the registered address and the payment
references are the three things that make a PDF look like a real company
issued it rather than something generated by a form.

The brand marks: `BRAND_NAME` is the PRODUCT and the seller name is the
COMPANY, and they are deliberately different strings in different places. A
founder's bank statement and the Terms they accepted both say GoXL Consulting
Solutions Pvt. Ltd.; the thing they bought is called GoXL Ally. Collapsing the
two would leave a receipt that cannot be matched to the charge it is for.
"""

from __future__ import annotations

from decimal import Decimal
from html import escape

from app.payments.invoice import Invoice
from app.payments.invoice_assets import (
    company_logo_data_uri,
    font_face_css,
    logo_data_uri,
)

#: The product lockup, matching the one the app's sidebar renders (see
#: PlatformLayout.jsx): the Ally mark, the product name with `Ally` in italic,
#: and the company line beneath it. Constants rather than configuration --
#: these are the product's own name, and a deployment that could rename the
#: product from an env var would be a deployment that could issue receipts
#: under a name nobody recognises.
BRAND_NAME_LEAD = "GoXL"
BRAND_NAME_TAIL = "Ally"
#: What sits under the wordmark. NOT "by GoXL Entrepreneurship": that is the
#: branding on the company's consulting invoices, and this document is for a
#: different thing entirely -- a founder's software subscription. Putting the
#: consulting brand on it would have a founder matching a Razorpay line for
#: GoXL Ally against a document headed by a business they never bought from.
#: The company itself is named where it belongs, in the footer, as the issuer.
BRAND_TAGLINE = "Founder clarity platform"

_CSS = """
@page{size:A4;margin:14mm 13mm;}
*{box-sizing:border-box;}
body{margin:0;background:#fff;color:#16241C;
  font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
  font-size:11.5px;line-height:1.55;
  -webkit-print-color-adjust:exact;print-color-adjust:exact;
  -webkit-font-smoothing:antialiased;}
.doc{max-width:184mm;margin:0 auto;}

/* --- header --- */
.top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;}
.lockup{display:flex;align-items:center;gap:11px;}
.lockup img{width:42px;height:42px;display:block;}
.wordmark{font-family:'Fraunces',Georgia,'Times New Roman',serif;
  font-size:21px;font-weight:600;color:#0E2A1B;letter-spacing:-.3px;line-height:1.1;}
.wordmark i{font-style:italic;color:#2D6A4F;}
.tagline{font-size:9.5px;color:#7A8A80;letter-spacing:.06em;
  text-transform:uppercase;font-weight:600;margin-top:3px;}
.docmeta{text-align:right;padding-top:2px;}
.doctitle{font-family:'Fraunces',Georgia,serif;font-size:17px;font-weight:600;
  color:#1B4332;letter-spacing:.4px;line-height:1.1;}
.docnum{font-size:12px;font-weight:700;color:#0E2A1B;margin-top:5px;
  letter-spacing:.02em;}
.docdate{font-size:10.5px;color:#7A8A80;margin-top:2px;}
.rule{height:2px;background:#1B4332;margin:13px 0 0;border-radius:2px;}

/* --- the amount, which is what the founder opened this to see --- */
.hero{margin-top:18px;background:#F4F8F5;border:1px solid #DDE8E0;
  border-radius:12px;padding:16px 20px;
  display:flex;justify-content:space-between;align-items:center;gap:18px;}
.hero-label{font-size:9.5px;text-transform:uppercase;letter-spacing:.11em;
  color:#6B7A70;font-weight:700;}
.hero-amount{font-family:'Fraunces',Georgia,serif;font-size:31px;font-weight:600;
  color:#0E2A1B;line-height:1.15;margin-top:3px;letter-spacing:-.5px;}
.hero-sub{font-size:10.5px;color:#6B7A70;margin-top:3px;}
.stamp{flex-shrink:0;text-align:center;border:1.5px solid #2D6A4F;color:#1B4332;
  border-radius:9px;padding:8px 16px;background:#fff;}
.stamp .word{font-family:'Fraunces',Georgia,serif;font-size:15px;font-weight:600;
  letter-spacing:.06em;text-transform:uppercase;line-height:1.1;}
.stamp .sub{font-size:8.5px;color:#6B7A70;letter-spacing:.07em;
  text-transform:uppercase;margin-top:2px;font-weight:600;}
.stamp.refunded{border-color:#C07A2E;color:#9A5312;}
.stamp.refunded .sub{color:#9A5312;}

/* --- parties --- */
.cols{display:flex;gap:18px;margin-top:20px;}
.col{flex:1;}
.col h2{margin:0 0 7px;font-size:9.5px;text-transform:uppercase;
  letter-spacing:.11em;color:#6B7A70;font-weight:700;}
.col .who{font-size:13px;font-weight:700;color:#0E2A1B;}
.col .line{color:#4A5A50;font-size:10.5px;word-break:break-word;}
.col .line.sub{color:#8A968E;font-size:9.5px;margin-top:4px;}
.col .line strong{color:#16241C;font-weight:650;}
dl.kv{margin:0;display:grid;grid-template-columns:auto 1fr;gap:3px 12px;font-size:10.5px;}
dl.kv dt{color:#7A8A80;margin:0;white-space:nowrap;}
dl.kv dd{margin:0;font-weight:600;color:#16241C;text-align:right;
  word-break:break-all;font-variant-numeric:tabular-nums;}

/* --- line items --- */
table.items{width:100%;border-collapse:collapse;margin-top:22px;}
table.items th{background:#1B4332;color:#fff;font-size:9px;text-transform:uppercase;
  letter-spacing:.1em;padding:9px 12px;text-align:left;font-weight:700;}
table.items th:first-child{border-radius:7px 0 0 0;}
table.items th:last-child{border-radius:0 7px 0 0;}
table.items td{padding:13px 12px;border-bottom:1px solid #E5DED2;vertical-align:top;}
table.items .num{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums;}
.item-name{font-weight:650;color:#0E2A1B;font-size:12px;}
.item-sub{display:block;color:#6B7A70;font-size:10px;margin-top:2px;}

/* --- totals --- */
.totals{margin-left:auto;width:78mm;margin-top:14px;font-size:11px;}
.totals .row{display:flex;justify-content:space-between;gap:16px;padding:4.5px 0;}
.totals .row span:last-child{font-variant-numeric:tabular-nums;font-weight:600;}
.totals .row.muted{color:#6B7A70;}
.totals .row.muted span:last-child{font-weight:500;}
.totals .row.discount{color:#1F7A4D;}
.totals .grand{border-top:1.5px solid #1B4332;margin-top:7px;padding-top:10px;
  font-family:'Fraunces',Georgia,serif;font-size:16px;font-weight:600;color:#0E2A1B;}
.totals .grand span:last-child{font-weight:600;}

.words{clear:both;margin-top:16px;padding:9px 13px;background:#FBF8F3;
  border-left:3px solid #2D6A4F;border-radius:0 7px 7px 0;font-size:10.5px;
  color:#16241C;font-weight:600;}
.words span{display:block;font-size:9px;text-transform:uppercase;
  letter-spacing:.11em;color:#6B7A70;font-weight:700;margin-bottom:2px;}

/* --- footer --- */
.foot{margin-top:30px;padding-top:13px;border-top:1px solid #E5DED2;}
.foot-top{display:flex;align-items:flex-start;gap:14px;}
.foot-mark{flex-shrink:0;width:96px;margin-top:1px;}
.foot-mark img{width:100%;height:auto;display:block;}
.foot-who{flex:1;min-width:0;}
.foot-name{font-size:11px;font-weight:700;color:#16241C;}
.foot-line{font-size:10px;color:#6B7A70;margin-top:2px;}
.foot-note{font-size:9.5px;color:#8A968E;margin-top:9px;line-height:1.6;}
.foot-thanks{font-family:'Fraunces',Georgia,serif;font-style:italic;
  font-size:12px;color:#2D6A4F;margin-top:11px;}
"""


def _rupees(amount: Decimal) -> str:
    """`12,345.00` -- Indian digit grouping, done here because Python's
    locale module cannot be relied on inside a container image that carries no
    locales. Two decimals always: a receipt showing `499` next to `499.00`
    elsewhere reads like two different numbers."""
    sign = "-" if amount < 0 else ""
    whole, _, frac = f"{abs(amount):.2f}".partition(".")
    if len(whole) > 3:
        head, tail = whole[:-3], whole[-3:]
        parts = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        whole = ",".join(parts + [tail])
    return f"{sign}{whole}.{frac}"


def _pct(value: Decimal) -> str:
    """`18`, not `18.0` -- and `2.5` when the rate really has a half.

    Decimal's `:g` keeps the trailing zero that the rate was configured with,
    which reads as a precision the tax rate does not have.
    """
    return f"{value.normalize():f}".rstrip("0").rstrip(".") or "0"


#: Indian numbering, because that is what the amounts are grouped in above.
_ONES = ("", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
         "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
         "Seventeen", "Eighteen", "Nineteen")
_TENS = ("", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety")


def _under_hundred(n: int) -> str:
    if n < 20:
        return _ONES[n]
    return (_TENS[n // 10] + (" " + _ONES[n % 10] if n % 10 else "")).strip()


def _words(n: int) -> str:
    """`59000` -> `Fifty Nine Thousand`. Lakh and crore, not million."""
    if n == 0:
        return "Zero"
    parts = []
    for divisor, label in ((10_000_000, "Crore"), (100_000, "Lakh"), (1_000, "Thousand"),
                           (100, "Hundred")):
        if n >= divisor:
            parts.append(f"{_words(n // divisor) if divisor == 10_000_000 else _under_hundred(n // divisor)} {label}")
            n %= divisor
    if n:
        parts.append(_under_hundred(n))
    return " ".join(p for p in parts if p.strip())


def amount_in_words(amount: Decimal) -> str:
    """"Seven Hundred Ninety Nine Rupees and Fifty Paise Only".

    On the document for the same reason the company's existing invoices carry
    it: a figure written out cannot be altered by changing one digit, and it
    is the line a reviewer checks the numerals against.
    """
    whole = int(amount)
    paise = int((amount - whole) * 100)
    text = f"{_words(whole)} Rupee{'' if whole == 1 else 's'}"
    if paise:
        text += f" and {_under_hundred(paise)} Paise"
    return text + " Only"


def _money(symbol: str, amount: Decimal) -> str:
    return f"{symbol}{_rupees(amount)}"


def _date(value) -> str:
    return value.strftime("%d %b %Y") if value else "—"


def _kv(pairs: list[tuple[str, str]]) -> str:
    """A definition list, skipping any row whose value is empty -- an invoice
    with a blank `Order ID:` label next to nothing looks like a bug in the
    document rather than a payment that simply had no order reference."""
    return "".join(
        f"<dt>{escape(k)}</dt><dd>{escape(v)}</dd>" for k, v in pairs if v
    )


def build_invoice_html(invoice: Invoice) -> str:
    """Render one Invoice to a complete HTML document."""
    symbol = "₹" if (invoice.currency or "INR").upper() == "INR" else ""
    tax = invoice.tax
    refunded = invoice.status == "refunded"
    place_of_supply = ""
    if tax and tax.place_of_supply:
        code = tax.place_of_supply_code
        place_of_supply = f"{tax.place_of_supply} ({code})" if code else tax.place_of_supply

    # The mark is optional by construction -- see invoice_assets.logo_data_uri.
    # The lockup reads correctly as pure typography without it, so an asset
    # that cannot be read costs a logo and not a receipt.
    logo = logo_data_uri()
    logo_img = f'<img src="{logo}" alt="">' if logo else ""

    # The ISSUER's mark, in the footer beside the legal entity -- the header
    # belongs to the product the founder actually bought. Optional the same
    # way: no mark costs a logo, never the receipt.
    company_logo = company_logo_data_uri()
    company_mark = (
        f'<div class="foot-mark"><img src="{company_logo}" alt=""></div>'
        if company_logo else ""
    )

    # WHO THE DOCUMENT IS ADDRESSED TO -- the one place the two kinds of buyer
    # actually differ. A business gets its registered name, its GSTIN and (when
    # supplied) its address, which is what its accountant needs to claim the
    # input credit; the person who paid is named underneath, because support
    # and the payment itself are still tied to them. A personal buyer gets
    # their own name and email and no registration, because they have none and
    # printing an empty "GSTIN:" label invites the question of why it is blank.
    if invoice.is_business:
        billed_to_label = "Billed to (business)"
        lines = [f'<div class="who">{escape(invoice.buyer_legal_name or "—")}</div>']
        if invoice.buyer_address:
            lines.append(f'<div class="line">{escape(invoice.buyer_address)}</div>')
        lines.append(
            f'<div class="line"><strong>GSTIN:</strong> {escape(invoice.buyer_gstin or "")}</div>')
        lines.append(
            f'<div class="line sub">Purchased by {escape(invoice.buyer_name or "")}'
            f' · {escape(invoice.buyer_email or "")}</div>')
        billed_to = "".join(lines)
    else:
        billed_to_label = "Billed to"
        billed_to = (f'<div class="who">{escape(invoice.buyer_name or "—")}</div>'
                     f'<div class="line">{escape(invoice.buyer_email or "")}</div>')

    details = _kv([
        ("Invoice no.", invoice.number),
        ("Payment ID", invoice.payment_reference or ""),
        ("Order ID", invoice.order_reference or ""),
        # The BUYER's state, which is what "place of supply" means under GST --
        # never the seller's, which is what an earlier draft of this document
        # wrongly printed here. It comes from `tax.place_of_supply`, frozen on
        # the payment row at checkout, and is simply absent on a payment taken
        # before the state was collected: an unclaimed place of supply is
        # visibly incomplete, where a guessed one is confidently wrong.
        ("Place of supply", place_of_supply),
        ("Country of supply", "India" if place_of_supply else ""),
    ])

    # The SAC column appears only on a tax invoice. A receipt claims no tax
    # classification, so printing a service code on it would imply one.
    sac_head = "<th>SAC</th>" if invoice.sac_code else ""
    sac_cell = f"<td>{escape(invoice.sac_code)}</td>" if invoice.sac_code else ""

    # What the line item is worth BEFORE tax on a tax invoice, and simply what
    # was charged on a receipt. The heading changes with the number so the
    # column never means two things under one name.
    line_amount = tax.taxable_value if tax else invoice.gross_amount
    amount_head = "Taxable value" if tax else "Amount"

    totals = []
    if invoice.list_amount is not None:
        totals.append(f'<div class="row muted"><span>Plan price</span>'
                      f'<span>{_money(symbol, invoice.list_amount)}</span></div>')
    if invoice.discount is not None:
        label = "Discount"
        if invoice.coupon_code:
            label = f"Discount ({invoice.coupon_code})"
        totals.append(f'<div class="row discount"><span>{escape(label)}</span>'
                      f'<span>−{_money(symbol, invoice.discount)}</span></div>')
    if tax:
        totals.append(f'<div class="row"><span>Taxable value</span>'
                      f'<span>{_money(symbol, tax.taxable_value)}</span></div>')
        half = _pct(tax.percent / 2)
        if tax.intra_state:
            totals.append(f'<div class="row muted"><span>CGST @ {half}%</span>'
                          f'<span>{_money(symbol, tax.cgst)}</span></div>')
            totals.append(f'<div class="row muted"><span>SGST @ {half}%</span>'
                          f'<span>{_money(symbol, tax.sgst)}</span></div>')
        else:
            totals.append(f'<div class="row muted"><span>IGST @ {_pct(tax.percent)}%</span>'
                          f'<span>{_money(symbol, tax.igst)}</span></div>')

    # The footer identifies the COMPANY. Assembled from whatever is configured
    # rather than a fixed set of lines, so an unset GSTIN or email leaves no
    # dangling separator behind it.
    foot_bits = [invoice.seller_address, invoice.seller_email]
    if invoice.seller_gstin:
        foot_bits.append(f"GSTIN: {invoice.seller_gstin}")
    if invoice.seller_pan:
        foot_bits.append(f"PAN: {invoice.seller_pan}")
    # Only on a tax invoice, and labelled as the SELLER's state so it cannot be
    # read as the place of supply (see the details block above).
    if tax and invoice.seller_state:
        foot_bits.append(f"State of supplier: {invoice.seller_state}")
    foot_line = escape(" · ".join(b for b in foot_bits if b))

    # The one sentence that has to be on a receipt with no GSTIN: it says what
    # the document IS, so nobody files a payment receipt as a tax invoice.
    note = (
        "This is a computer-generated tax invoice and does not require a signature. "
        f"The amount shown is inclusive of GST at {_pct(tax.percent)}%."
        if tax else
        "This is a computer-generated payment receipt and does not require a "
        "signature. It is a record of payment, not a tax invoice, and no GST "
        "has been charged or is claimable against it."
    )
    if refunded:
        note += (" This payment was subsequently refunded; the document is retained "
                 "as the record of the original charge.")

    stamp_word = "Refunded" if refunded else "Paid"
    stamp_sub = "see note" if refunded else "in full"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{escape(invoice.document_title)} {escape(invoice.number)}</title>
<style>{font_face_css()}{_CSS}</style></head>
<body><div class="doc">

  <div class="top">
    <div class="lockup">
      {logo_img}
      <div>
        <div class="wordmark">{BRAND_NAME_LEAD} <i>{BRAND_NAME_TAIL}</i></div>
        <div class="tagline">{BRAND_TAGLINE}</div>
      </div>
    </div>
    <div class="docmeta">
      <div class="doctitle">{escape(invoice.document_title)}</div>
      <div class="docnum">{escape(invoice.number)}</div>
      <div class="docdate">{escape(_date(invoice.issued_at))}</div>
    </div>
  </div>
  <div class="rule"></div>

  <div class="hero">
    <div>
      <div class="hero-label">Amount paid</div>
      <div class="hero-amount">{_money(symbol, invoice.gross_amount)}</div>
      <div class="hero-sub">
        {escape(invoice.billing_cycle)} · Paid on {escape(_date(invoice.paid_at))} via Razorpay
      </div>
    </div>
    <div class="stamp{' refunded' if refunded else ''}">
      <div class="word">{stamp_word}</div>
      <div class="sub">{stamp_sub}</div>
    </div>
  </div>

  <div class="cols">
    <div class="col">
      <h2>{billed_to_label}</h2>
      {billed_to}
    </div>
    <div class="col">
      <h2>Details</h2>
      <dl class="kv">{details}</dl>
    </div>
  </div>

  <table class="items">
    <thead><tr>
      <th>Description</th>{sac_head}<th class="num">{amount_head}</th>
    </tr></thead>
    <tbody><tr>
      <td>
        <span class="item-name">{escape(invoice.description)}</span>
        <span class="item-sub">{escape(invoice.billing_cycle)}</span>
      </td>
      {sac_cell}
      <td class="num">{_money(symbol, line_amount)}</td>
    </tr></tbody>
  </table>

  <div class="totals">
    {''.join(totals)}
    <div class="row grand"><span>Total paid</span>
      <span>{_money(symbol, invoice.gross_amount)}</span></div>
  </div>

  <div class="words"><span>Total in words</span>
    {escape(amount_in_words(invoice.gross_amount))}</div>

  <div class="foot">
    <div class="foot-top">
      {company_mark}
      <div class="foot-who">
        <div class="foot-name">{escape(invoice.seller_name)}</div>
        <div class="foot-line">{foot_line}</div>
      </div>
    </div>
    <div class="foot-note">{escape(note)}</div>
    <div class="foot-thanks">Thank you for building with Ally.</div>
  </div>

</div></body></html>"""
