"""Render the ER Diagram & Data Dictionary from schema.json + descriptions.py.

Textual, not drawn: relationships are written as an index of every foreign key
rather than as a picture, which is what the July 2026 document did and what was
asked for again. A text ER survives copy-paste into Word, diffs in git, and can
be searched for a column name -- none of which a PNG does.

Run:  python3 scripts/docs/render_er.py <schema.json> > ER_Diagram.md
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import descriptions as D  # noqa: E402

PREV = {"tables": 48, "fks": 70, "date": "July 2026"}
# The July 2026 Entity Mapping document's own stated counts, for the drift table.
PREV_ROWS = {
    "questions": 208, "problems": 124, "root_causes": 807,
    "interventions": 97, "industries": 4, "blind_spots": 20,
    "agent_interpretations": 31, "frameworks": 83,
}


def key_badge(col: str, t: dict) -> str:
    bits = []
    if col in t["pk"]:
        bits.append("PK")
    for fk in t["fks"]:
        if col in fk["cols"]:
            bits.append(f"FK -> {fk['ref_table']}")
    for u in t["uniques"]:
        if col in u["cols"]:
            bits.append("UQ")
    return ", ".join(bits) or "--"


def req(c: dict) -> str:
    if c["default"] and "nextval" in str(c["default"]):
        return "Auto"
    if not c["nullable"]:
        return "Yes"
    return "No"


def note(tbl: str, c: dict) -> str:
    hand = D.COLUMNS.get(tbl, {}).get(c["name"], "")
    if hand:
        return hand
    if c["comment"].strip():
        return c["comment"].strip()
    d = c["default"]
    if d and "nextval" not in str(d):
        return f"Defaults to `{d}`."
    return ""


def main() -> int:
    data = json.load(open(sys.argv[1]))
    T = data["tables"]
    blurbs = data["part_blurbs"]
    by_part: dict[str, list[str]] = defaultdict(list)
    for name, t in T.items():
        by_part[t["part"]].append(name)

    o: list[str] = []
    w = o.append

    w("# Founder Alley — Entity Relationship Diagram")
    w("")
    w("**GoXL Consulting Solutions Pvt. Ltd.**  ")
    w("*Clarity Before Action*")
    w("")
    w("CONFIDENTIAL — INTERNAL USE ONLY")
    w("")
    w(f"Version 2 · {data['totals']['tables']} tables · "
      f"{data['totals']['foreign_keys']} foreign key relationships · "
      f"{data['totals']['columns']} columns · complete reference")
    w("")
    w("| | |")
    w("| --- | --- |")
    w("| **Schema revision** | "
      f"`{data['alembic_head']}` (Alembic head) |")
    w(f"| **Generated** | {data['generated_at'][:19].replace('T', ' ')} |")
    w("| **Source of truth** | The migrated database at the revision above |")
    w("| **Supersedes** | "
      f"Entity Relationship Diagram, {PREV['date']} ({PREV['tables']} tables) |")
    w("")

    # ---- why the database is the source ---------------------------------
    w("## How this document is produced")
    w("")
    w("Generated by `scripts/docs/render_er.py` from a live read of the "
      "migrated database. Re-run it after any migration and the document is "
      "current; nothing here is transcribed by hand except the descriptions, "
      "which live in `scripts/docs/descriptions.py`.")
    w("")
    w("**It reads the database rather than the ORM, deliberately.** There is "
      "no single metadata object that covers this schema. Measured at this "
      "revision:")
    w("")
    w("- `app/models/schema.py` alone registers **69** of 104 tables")
    w("- importing all eighteen model modules — `app/models/*.py` plus a "
      "`db_models.py` inside eight feature packages, all sharing the one "
      "`Base` in `app/db/session.py` — reaches **81**")
    w("- **23 tables have no SQLAlchemy model at all** and are reached only "
      "by raw SQL")
    w("")
    w("So no import gives the whole schema, and a document built from one "
      "would quietly omit whatever its Base could not see. The database is "
      "the only complete answer, which is what this reads. The 23 "
      "model-less tables are listed in Appendix B.")
    w("")

    # ---- what changed ---------------------------------------------------
    w("## What changed since the July 2026 version")
    w("")
    w(f"The previous document described **{PREV['tables']} tables** and "
      f"**{PREV['fks']} foreign keys**. The schema has roughly doubled, and "
      "the content banks have grown by far more than that.")
    w("")
    w("| | July 2026 | Now | Change |")
    w("| --- | --: | --: | --- |")
    w(f"| Tables | {PREV['tables']} | {data['totals']['tables']} | "
      f"+{data['totals']['tables'] - PREV['tables']} |")
    w(f"| Foreign keys | {PREV['fks']} | {data['totals']['foreign_keys']} | "
      f"+{data['totals']['foreign_keys'] - PREV['fks']} |")
    w(f"| Columns | not stated | {data['totals']['columns']} | — |")
    w("")
    w("Row counts in the content banks, which is where the growth really is:")
    w("")
    w("| Table | July 2026 | Now | Change |")
    w("| --- | --: | --: | --- |")
    for tbl, old in sorted(PREV_ROWS.items(), key=lambda kv: -T[kv[0]]["rows"]):
        now = T[tbl]["rows"]
        if now == old:
            delta = "unchanged"
        elif now == 0:
            # Not a deletion: the table is simply not seeded in this database.
            # Rendering it as a multiplier read as if the data had been lost.
            delta = "**not seeded here** -- see Appendix A"
        elif old:
            delta = f"x{now / old:.1f}"
        else:
            delta = "new"
        w(f"| `{tbl}` | {old:,} | {now:,} | {delta} |")
    w("")
    w("The question bank is the headline: **208 questions became "
      f"{T['questions']['rows']:,}**, and it gained a fourth stage group "
      "(Exit) plus the six scope columns that decide who may be asked what.")
    w("")

    # ---- legend ---------------------------------------------------------
    w("## Legend")
    w("")
    w("| Marker | Meaning |")
    w("| --- | --- |")
    w("| **PK** | Primary key |")
    w("| **FK -> table** | Foreign key, and the table it points at |")
    w("| **UQ** | Part of a unique constraint |")
    w("| Req = Yes | `NOT NULL` |")
    w("| Req = No | Nullable |")
    w("| Req = Auto | Generated by the database (sequence default) |")
    w("")
    w("Row counts are from the local database at this revision. For the "
      "Part A content banks these are the seeded reference data and match "
      "production. For founder data they are test rows and carry no "
      "production meaning.")
    w("")

    # ---- summary --------------------------------------------------------
    w("## Table summary")
    w("")
    w(f"All {data['totals']['tables']} tables, grouped into "
      f"{len(by_part)} parts.")
    w("")
    w("| # | Table | Part | Cols | Rows | Purpose |")
    w("| --: | --- | --- | --: | --: | --- |")
    n = 0
    for part in sorted(by_part):
        for name in sorted(by_part[part]):
            n += 1
            t = T[name]
            purpose = D.TABLES.get(name) or "— not yet described —"
            short = purpose.split(". ")[0].rstrip(".")
            if len(short) > 95:
                short = short[:92] + "..."
            w(f"| {n} | `{name}` | {part} | {len(t['columns'])} | "
              f"{t['rows']:,} | {short} |")
    w("")

    # ---- relationship index (the textual ER) ----------------------------
    w("## Relationship index")
    w("")
    w(f"Every one of the {data['totals']['foreign_keys']} foreign keys, as "
      "`child.column -> parent`. This is the entity-relationship map in text "
      "form: read down the Parent column to find everything that depends on "
      "a table, and down Child to find everything a table depends on.")
    w("")
    w("| Child table | Column(s) | Parent table | On delete |")
    w("| --- | --- | --- | --- |")
    rels = []
    for name in sorted(T):
        for fk in T[name]["fks"]:
            od = "CASCADE" if "ON DELETE CASCADE" in fk["def"] else (
                "SET NULL" if "ON DELETE SET NULL" in fk["def"] else "restrict")
            rels.append((name, ", ".join(f"`{c}`" for c in fk["cols"]),
                         fk["ref_table"], od))
    for child, cols, parent, od in rels:
        w(f"| `{child}` | {cols} | `{parent}` | {od} |")
    w("")

    # most-referenced tables
    ref_count: dict[str, int] = defaultdict(int)
    for _, _, parent, _ in rels:
        ref_count[parent] += 1
    w("**Most-referenced tables** — the hubs of the schema:")
    w("")
    w("| Table | Referenced by |")
    w("| --- | --: |")
    for tbl, c in sorted(ref_count.items(), key=lambda kv: -kv[1])[:10]:
        w(f"| `{tbl}` | {c} tables |")
    w("")

    # ---- per-part detail ------------------------------------------------
    num = 0
    for part in sorted(by_part):
        title, blurb = blurbs[part]
        w("---")
        w("")
        w(f"## Part {part} — {title}")
        w("")
        w(blurb)
        w("")
        nt = len(by_part[part])
        w(f"*{nt} {'table' if nt == 1 else 'tables'}.*")
        w("")
        for name in sorted(by_part[part]):
            num += 1
            t = T[name]
            w(f"### Table {num} — `{name}`")
            w("")
            w(D.TABLES.get(name) or "— not yet described —")
            w("")
            meta = [f"{len(t['columns'])} columns", f"{t['rows']:,} rows"]
            if t["pk"]:
                meta.append("PK " + ", ".join(f"`{c}`" for c in t["pk"]))
            else:
                meta.append("**no primary key**")
            w("*" + " · ".join(meta) + "*")
            w("")
            w("| Field | Type | Req | Key | Notes |")
            w("| --- | --- | --- | --- | --- |")
            for c in t["columns"]:
                nt = note(name, c).replace("|", "\\|")
                w(f"| `{c['name']}` | {c['type']} | {req(c)} | "
                  f"{key_badge(c['name'], t)} | {nt} |")
            w("")
            checks = [ch for ch in t["checks"] if "NOT NULL" not in ch["def"]]
            if checks:
                w("**Constraints**")
                w("")
                for ch in checks:
                    w(f"- `{ch['name']}` — `{ch['def']}`")
                w("")
            if t["uniques"]:
                w("**Unique**")
                w("")
                for u in t["uniques"]:
                    w(f"- `{u['name']}` on "
                      + ", ".join(f"`{c}`" for c in u["cols"]))
                w("")

    # ---- appendices -----------------------------------------------------
    w("---")
    w("")
    w("## Appendix A — Environment drift")
    w("")
    w("The three environments are not identical, and a document that did not "
      "say so would be misleading. Measured 3 October 2026:")
    w("")
    w("| | Local (this document) | Supabase `founder-alley` | Production (AWS) |")
    w("| --- | --- | --- | --- |")
    w(f"| Alembic revision | `{data['alembic_head']}` | `f8a3c26e4b91` | "
      "reported at head |")
    w(f"| Tables | {data['totals']['tables']} | 139 | not measured |")
    w(f"| Questions | {T['questions']['rows']:,} | 5,140 | not measured |")
    w("")
    w("Three things worth knowing about that:")
    w("")
    w("1. **Supabase sits on an orphan revision.** `f8a3c26e4b91` came from "
      "an unmerged branch (`claude/checkout-gst-billing`) and does not exist "
      "in the repository. Its real parent, `e5b2d47a91c3`, is 49 revisions "
      "behind head.")
    w("2. **Supabase has 39 tables this database does not** — mostly monthly "
      "partitions of `messages`, `analytics_events` and `audit_logs`, which "
      "are created by partition management rather than by a migration, plus "
      "`access_settings`, `beta_users` and `_perf_baseline`.")
    w("3. **Some reference data is seeded in Supabase but not here.** "
      "`agent_interpretations` holds 31 rows there and none in this "
      "database, so a figure of 0 in this document means unseeded locally, "
      "not deleted.")
    w("4. **The surrogate keys have diverged.** `questions`, `problems` and "
      "`root_causes` hold different id sets in the two databases, so no row "
      "can be copied between them by id. `question_code` and its equivalents "
      "are the only safe join keys across environments.")
    w("")
    w("## Appendix B — Tables with no ORM model")
    w("")
    w("These 23 tables are reached only by raw SQL. That is not necessarily "
      "wrong — reference data read once at startup does not need a model — "
      "but it is worth knowing, because a schema change here will not be "
      "caught by anything that type-checks the models.")
    w("")
    for t in ["admin_audit_log", "alembic_version", "broadcast_reads",
              "broadcasts", "chronic_state_inference", "coupon_redemptions",
              "coupons", "daily_token_usage", "feature_flag_overrides",
              "feature_flags", "founder_daily_quotes",
              "founder_dimension_profile", "founder_dimensions",
              "founder_settings", "notification_types", "plan_call_usage",
              "psychological_state_signals", "question_industry_mapping",
              "session_context_facts", "session_state_bands",
              "support_bot_answers", "support_bot_misses", "unbilled_usage"]:
        w(f"- `{t}`")
    w("")
    w("`question_industry_mapping` is the one to look at first: 3,630 rows, "
      "core to industry question selection, and no model.")
    w("")
    w("## Appendix C — Tables holding no rows")
    w("")
    w("Empty in this database. Some are features not yet in use; some are "
      "superseded; most are simply unexercised because this is a test "
      "database. Listed so nobody mistakes an empty table for a missing one.")
    w("")
    empty = sorted(n for n, t in T.items() if t["rows"] == 0)
    w(", ".join(f"`{n}`" for n in empty))
    w("")
    w(f"*{len(empty)} of {len(T)} tables.* Three are superseded rather than "
      "unused: `business_dimensions`, `founder_dimensions` and "
      "`founder_dimension_profile`.")
    w("")

    print("\n".join(o))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
