"""expand industries and add industry relevance

Revision ID: 62ebd946ebc0
Revises: 719a012becf1
Create Date: 2026-09-18 17:58

"""

from typing import Sequence, Union

from alembic import op


revision: str = "62ebd946ebc0"
down_revision: Union[str, Sequence[str], None] = "719a012becf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    statements = [
        r"""INSERT INTO industries (industry_id, industry_code, industry_name, industry_subtitle, why_industry_context_matters, description, defining_characteristics, empathy_language, top_pain_points, top_pain_point_weights, key_metrics, red_flags, recommended_benchmarks, diagnostic_adjustments, red_flags_description, stage_thresholds_inr)
VALUES
(5, 'agritech', 'Agriculture & AgriTech', 'Farming operations, agri-input companies, farm-to-market platforms, agri-fintech, precision farming, cold chain and post-harvest tech', 'Revenue is seasonal and weather-dependent in ways no software business experiences -- a founder here needs different cash flow and risk questions than a SaaS founder.',
 'Farming operations, agri-input companies (seeds, fertilizer, pesticides), farm-to-market platforms, agri-fintech (crop loans, insurance), precision farming and IoT-based farm tech, cold chain and post-harvest management, and farmer-producer organisation (FPO) platforms. Revenue is tied directly to harvest cycles and monsoon patterns, not steady monthly demand. Growth here depends on trust built at the village or district level, not digital marketing alone.',
 '["India has over 140 million farm holdings, mostly small and fragmented (under 2 hectares), which makes single-farmer sales models expensive to scale -- most successful AgriTech founders build through aggregation (FPOs, cooperatives) rather than direct-to-farmer", "Government schemes like PM-KISAN, PM Fasal Bima Yojana, and state-specific subsidy programs directly shape farmer purchasing power and timing -- a founder who does not track scheme cycles will misread demand patterns", "Monsoon dependency still drives the bulk of Indian farm income; a poor monsoon year can silently collapse a founder''s entire customer base regardless of product quality", "Trust in agri-input and agri-tech purchases is still heavily influenced by the local dealer network and word-of-mouth within a village -- digital-only distribution strategies imported from urban D2C playbooks often fail here"]'::jsonb,
 '{"use": ["farmer", "harvest cycle", "yield", "input cost", "mandi", "procurement", "FPO", "cold chain"], "avoid": [{"say": "farmer", "instead_of": "customer"}, {"say": "harvest season", "instead_of": "quarter"}], "psychological_framing": "Acknowledge that AgriTech founders are often working against forces completely outside their control -- weather, government policy, fragmented land ownership. Avoid framing slow traction as a pure execution failure; validate that the operating environment itself is genuinely harder than urban B2B or B2C contexts."}'::jsonb,
 '[{"weight": "CRITICAL", "pain_point_name": "Farmer Trust and Adoption Gap", "indian_specific_nuance": "Farmers are risk-averse by necessity -- a failed crop from an unfamiliar product or method can mean real financial ruin, so adoption of anything new moves far slower than urban markets", "why_high_risk_in_this_vertical": "AgriTech products often assume adoption speed similar to consumer apps, but real behaviour change with farmers can take multiple full crop cycles to earn trust"}, {"weight": "CRITICAL", "pain_point_name": "Seasonal and Monsoon-Dependent Revenue", "indian_specific_nuance": "Most agri-businesses see extreme revenue concentration around 2-3 harvest windows a year, with long quiet periods between", "why_high_risk_in_this_vertical": "Founders who build cash flow plans assuming steady monthly revenue, like a SaaS model, run out of runway during the off-season"}, {"weight": "HIGH", "pain_point_name": "Fragmented Last-Mile Distribution", "indian_specific_nuance": "Reaching farmers in tier 3 and tier 4 towns and villages requires physical distribution networks, local dealers, or field agents -- there is no simple digital-only channel", "why_high_risk_in_this_vertical": "Founders who scale their tech quickly often cannot scale their last-mile physical presence at the same pace, creating a demand-fulfillment gap"}, {"weight": "HIGH", "pain_point_name": "Dependence on Government Scheme Timing", "indian_specific_nuance": "Farmer purchasing power often spikes around subsidy disbursement or crop insurance payout windows, which shift year to year based on policy", "why_high_risk_in_this_vertical": "Founders who plan launches or campaigns without tracking scheme calendars can badly misjudge demand timing"}, {"weight": "MEDIUM-HIGH", "pain_point_name": "Post-Harvest Loss and Cold Chain Gaps", "indian_specific_nuance": "India loses a significant share of perishable produce due to weak cold storage and transport infrastructure, especially outside major cities", "why_high_risk_in_this_vertical": "Founders in the fresh produce or cold chain space face structural infrastructure risk that no amount of product improvement alone can fix"}, {"weight": "MEDIUM", "pain_point_name": "Land Ownership and Data Ambiguity", "indian_specific_nuance": "Land records in India are often outdated, disputed, or informally held through tenant farming or shared family land, making it hard to build clean farmer or land databases", "why_high_risk_in_this_vertical": "AgriTech products relying on land-size or ownership data for credit scoring or targeting can be working from unreliable base data"}]'::jsonb,
 '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),

(6, 'automotive', 'Automotive & Mobility', 'Vehicle manufacturers, EV startups, auto components, ride-sharing, fleet management, automotive aftermarket', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(7, 'fintech', 'Banking, Financial Services & Insurance / FinTech', 'Digital lending, payments, insurtech, wealthtech, neobanks, embedded finance, BNPL', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(8, 'beauty_personal_care', 'Beauty & Personal Care', 'Cosmetics brands, skincare D2C, salons and spas, personal grooming products, wellness beauty tech', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(9, 'proptech', 'Construction & Real Estate / PropTech', 'Real estate developers, construction tech, property management platforms, co-working and rental marketplaces, architecture and interior design firms', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(10, 'consumer_electronics', 'Consumer Electronics', 'Hardware startups, IoT devices, wearables, smart home products, electronics manufacturing', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(11, 'ecommerce_d2c', 'E-commerce & D2C', 'Online retail brands, marketplace sellers, subscription commerce, quick commerce, D2C consumer brands', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(12, 'edtech', 'Education & EdTech', 'Online learning platforms, tutoring marketplaces, skilling and upskilling, school and college software, test prep', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(13, 'cleantech_energy', 'Energy, CleanTech & Renewables', 'Solar and renewable energy providers, EV charging infrastructure, energy storage, carbon and sustainability tech', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(14, 'media_entertainment', 'Entertainment & Media', 'Content studios, streaming platforms, creator economy tools, publishing, music and film production', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(15, 'fashion_apparel', 'Fashion & Apparel', 'Clothing brands, footwear, accessories, textile-based D2C, fashion marketplaces', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(16, 'foodtech', 'Food & Beverage / FoodTech', 'Restaurants, cloud kitchens, packaged food brands, beverage companies, food delivery and discovery platforms', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(17, 'gaming', 'Gaming', 'Mobile game studios, esports platforms, gaming infrastructure, in-game economy and monetisation tools', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(18, 'healthtech', 'Healthcare & HealthTech / MedTech', 'Telemedicine, diagnostics, hospital software, medical devices, health insurance tech, wellness platforms', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(19, 'travel_hospitality', 'Hospitality, Travel & Tourism', 'Hotels, travel booking platforms, tour operators, vacation rentals, travel-tech', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(20, 'hrtech', 'Human Resources & HRTech', 'Recruitment platforms, payroll and HR software, employee engagement tools, staffing and gig-work platforms', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(21, 'trade_import_export', 'Import/Export & Trade', 'Import-export businesses, trading companies, cross-border commerce, customs and trade compliance services', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(22, 'legaltech', 'Legal & LegalTech', 'Law firms, legal-tech platforms, contract management software, compliance and regulatory tech', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(23, 'logistics', 'Logistics & Supply Chain', 'Freight and shipping companies, warehousing, last-mile delivery, supply chain software, fleet tech', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(24, 'adtech_marketing', 'Marketing, Advertising & AdTech', 'Digital marketing agencies, ad-tech platforms, martech tools, influencer marketing platforms, PR firms', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(25, 'pharma_biotech', 'Pharmaceuticals & Biotech', 'Drug development, biotech research, pharmaceutical manufacturing, clinical research organisations', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(26, 'retail', 'Retail', 'Brick-and-mortar retail chains, franchise businesses, omni-channel retail, specialty stores', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(27, 'sports_fitness', 'Sports, Fitness & Wellness', 'Gyms and fitness studios, sports tech, wellness apps, nutrition and supplement brands, sports leagues and events', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(28, 'telecom', 'Telecommunications', 'Telecom operators, network infrastructure providers, telecom software and billing platforms', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(29, 'textiles', 'Textiles', 'Textile manufacturers, fabric and yarn producers, textile exporters, garment manufacturing', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb),
(30, 'transport_delivery', 'Transportation & Delivery', 'Ride-hailing, delivery platforms, freight aggregators, fleet and driver management tech', 'PLACEHOLDER -- full profile not yet written.', 'PLACEHOLDER -- full profile not yet written.', '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, NULL, '{}'::jsonb)""",
        r"""SELECT setval('industries_industry_id_seq', (SELECT MAX(industry_id) FROM industries))""",
        r"""ALTER TABLE questions ADD COLUMN IF NOT EXISTS industry_relevance jsonb DEFAULT '["all"]'::jsonb""",
        r"""UPDATE questions SET industry_relevance = '["all"]'::jsonb WHERE industry_relevance IS NULL""",
        r"""ALTER TABLE root_causes ADD COLUMN IF NOT EXISTS industry_relevance jsonb DEFAULT '["all"]'::jsonb""",
        r"""UPDATE root_causes SET industry_relevance = '["all"]'::jsonb WHERE industry_relevance IS NULL""",
        r"""ALTER TABLE problems ADD COLUMN IF NOT EXISTS industry_relevance jsonb DEFAULT '["all"]'::jsonb""",
        r"""UPDATE problems SET industry_relevance = '["all"]'::jsonb WHERE industry_relevance IS NULL"""
    ]

    for statement in statements:
        bind.exec_driver_sql(statement)


def downgrade() -> None:
    # Intentionally irreversible:
    # this migration adds reference data and columns that may be used by
    # production rows immediately after launch. Removing them automatically
    # could destroy or orphan data.
    raise RuntimeError(
        "Migration 62ebd946ebc0 is intentionally irreversible. "
        "Rollback the application without downgrading this database migration."
    )
